server:
  port: 8082

spring:
  application:
    name: smart-approval-manage
  datasource:
    url: jdbc:mysql://localhost:3306/smart_meeting?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 13831358448
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: ${JWT_SECRET:medical-meeting-2026-secret-2026}
  expiration: 86400000
